version: '3.3'

networks:
  netAuthelia:
    driver: bridge

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    networks:
      - netAuthelia
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      ## In production the healthcheck section should be commented.
      disable: true
    environment:
      - TZ=Europe/Paris

  redis:
    image: redis:alpine
    container_name: redisAuthelia
    volumes:
      - ./redis:/data
    networks:
      - netAuthelia
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
