services:
  outlineRedis:
    image: redis
    restart: always
    container_name: outlineredis
    networks:
      - outline-internal
    
  outline:
    image: outlinewiki/outline:latest
    user: root
    restart: always
    container_name: outline
    command: sh -c "yarn start --env=production-ssl-disabled"
    depends_on:
      - outlineRedis
      - outlineMinio
    networks:
      - outline-internal
      - reverseproxy-nw
networks:
  outline-internal:
  reverseproxy-nw:
    external: true
